version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: security_db
    restart: always
    networks:
      - security
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: security_master
      MYSQL_USER: admin
      MYSQL_PASSWORD: B4u
      MYSQL_ROOT_PASSWORD: rktirtho

  app:
    image: rktirtho/jwt-authentication:8.0.4
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/security_master
      - spring.datasource.username=admin
      - spring.datasource.password=B4u
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - security


networks:
  security: